from __future__ import annotations

# Neutral, brand-independent default templates.
# The frontend can import these through the WebSocket state response.
TEMPLATES: list[dict] = [
    {"id": "heat_pump_filter", "name": "Wärmepumpenfilter", "category": "heating", "area_name": "Technikraum", "icon": "mdi:air-filter", "interval": 90, "interval_unit": "days", "priority": 2, "description": "Filter der Wärmepumpe prüfen oder wechseln."},
    {"id": "heating_service", "name": "Heizungswartung", "category": "heating", "area_name": "Technikraum", "icon": "mdi:heat-pump-outline", "interval": 365, "interval_unit": "days", "priority": 5, "description": "Jährliche Wartung der Heizungsanlage."},
    {"id": "expansion_vessel", "name": "Ausdehnungsgefäß prüfen", "category": "heating", "area_name": "Technikraum", "icon": "mdi:gauge", "interval": 365, "interval_unit": "days", "priority": 4, "description": "Druck und Zustand des Ausdehnungsgefäßes prüfen."},
    {"id": "radiator_bleed", "name": "Heizkörper entlüften", "category": "heating", "area_name": "Haus", "icon": "mdi:radiator", "interval": 180, "interval_unit": "days", "priority": 2, "description": "Heizkörper auf Luft prüfen und bei Bedarf entlüften."},
    {"id": "underfloor_heating_manifold", "name": "Fußbodenheizung Verteiler prüfen", "category": "heating", "area_name": "Haus", "icon": "mdi:pipe-valve", "interval": 365, "interval_unit": "days", "priority": 3, "description": "Verteiler, Durchfluss und Ventile prüfen."},

    {"id": "ventilation_filter", "name": "Lüftungsfilter", "category": "ventilation", "area_name": "Haus", "icon": "mdi:fan", "interval": 180, "interval_unit": "days", "priority": 3, "description": "Filter der Lüftungsanlage prüfen oder wechseln."},
    {"id": "extractor_filter", "name": "Dunstabzug Filter", "category": "ventilation", "area_name": "Küche", "icon": "mdi:air-filter", "interval": 90, "interval_unit": "days", "priority": 2, "description": "Fettfilter reinigen oder tauschen."},
    {"id": "bathroom_fan_clean", "name": "Badlüfter reinigen", "category": "ventilation", "area_name": "Bad", "icon": "mdi:fan-alert", "interval": 180, "interval_unit": "days", "priority": 2, "description": "Lüfterabdeckung und Staub entfernen."},

    {"id": "water_filter", "name": "Hauswasserfilter", "category": "water", "area_name": "Hausanschlussraum", "icon": "mdi:water-pump", "interval": 180, "interval_unit": "days", "priority": 4, "description": "Hauswasserfilter prüfen oder wechseln."},
    {"id": "softener_salt", "name": "Enthärtungsanlage Salz prüfen", "category": "water", "area_name": "Hausanschlussraum", "icon": "mdi:shaker-outline", "interval": 30, "interval_unit": "days", "priority": 3, "description": "Salzstand prüfen und bei Bedarf auffüllen."},
    {"id": "siphon_clean", "name": "Siphons reinigen", "category": "water", "area_name": "Haus", "icon": "mdi:pipe-disconnected", "interval": 180, "interval_unit": "days", "priority": 2, "description": "Siphons auf Ablagerungen prüfen und reinigen."},
    {"id": "main_water_valve", "name": "Hauptwasserhahn bewegen", "category": "water", "area_name": "Hausanschlussraum", "icon": "mdi:valve", "interval": 365, "interval_unit": "days", "priority": 3, "description": "Hauptabsperrung kurz bewegen, damit sie nicht festsetzt."},
    {"id": "outdoor_tap_winter", "name": "Außenwasser winterfest machen", "category": "water", "area_name": "Außenbereich", "icon": "mdi:pipe-valve", "interval": 365, "interval_unit": "days", "priority": 4, "description": "Außenwasser abstellen und Leitungen entleeren."},

    {"id": "rcd_test", "name": "FI-Schutzschalter Test", "category": "electrical", "area_name": "Haus", "icon": "mdi:lightning-bolt-outline", "interval": 180, "interval_unit": "days", "priority": 5, "description": "FI/RCD-Testtaste auslösen und Funktion prüfen."},
    {"id": "distribution_box_check", "name": "Sicherungskasten Sichtprüfung", "category": "electrical", "area_name": "Hausanschlussraum", "icon": "mdi:fuse", "interval": 365, "interval_unit": "days", "priority": 4, "description": "Sichtprüfung auf Wärme, Geruch, lose Abdeckungen und Beschriftung."},
    {"id": "surge_protection", "name": "Überspannungsschutz prüfen", "category": "electrical", "area_name": "Hausanschlussraum", "icon": "mdi:flash-triangle-outline", "interval": 365, "interval_unit": "days", "priority": 4, "description": "Statusanzeigen des Überspannungsschutzes prüfen."},
    {"id": "ups_battery_test", "name": "USV Batterie-Test", "category": "electrical", "area_name": "IT/Netzwerk", "icon": "mdi:battery-clock-outline", "interval": 180, "interval_unit": "days", "priority": 3, "description": "USV Selbsttest ausführen und Batteriestatus prüfen."},

    {"id": "smoke_detector_test", "name": "Rauchmelder-Test", "category": "safety", "area_name": "Haus", "icon": "mdi:smoke-detector-outline", "interval": 180, "interval_unit": "days", "priority": 5, "description": "Funktionstest aller Rauchmelder."},
    {"id": "fire_extinguisher_check", "name": "Feuerlöscher Sichtprüfung", "category": "safety", "area_name": "Haus", "icon": "mdi:fire-extinguisher", "interval": 365, "interval_unit": "days", "priority": 4, "description": "Druckanzeige, Plombe und Standort prüfen."},
    {"id": "co_detector_test", "name": "CO-Melder Test", "category": "safety", "area_name": "Haus", "icon": "mdi:molecule-co", "interval": 180, "interval_unit": "days", "priority": 5, "description": "CO-Melder testen und Batteriestand prüfen."},
    {"id": "first_aid_check", "name": "Erste-Hilfe-Set prüfen", "category": "safety", "area_name": "Haus", "icon": "mdi:medical-bag", "interval": 365, "interval_unit": "days", "priority": 3, "description": "Ablaufdaten und Vollständigkeit prüfen."},
    {"id": "alarm_system_test", "name": "Alarmanlage Funktionstest", "category": "safety", "area_name": "Haus", "icon": "mdi:shield-home-outline", "interval": 180, "interval_unit": "days", "priority": 4, "description": "Sensoren, Sirene und Benachrichtigung testen."},

    {"id": "solar_storage_check", "name": "Solarspeicher Sichtprüfung", "category": "solar", "area_name": "Technikraum", "icon": "mdi:home-battery-outline", "interval": 180, "interval_unit": "days", "priority": 3, "description": "Solarspeicher, Statusanzeigen und Fehlermeldungen prüfen."},
    {"id": "pv_inverter_check", "name": "PV-Wechselrichter Sichtprüfung", "category": "solar", "area_name": "Technikraum", "icon": "mdi:solar-power-variant-outline", "interval": 180, "interval_unit": "days", "priority": 3, "description": "Wechselrichterstatus und Fehlerspeicher prüfen."},
    {"id": "pv_yield_review", "name": "PV-Ertrag plausibilisieren", "category": "solar", "area_name": "Haus", "icon": "mdi:chart-line", "interval": 30, "interval_unit": "days", "priority": 2, "description": "Monatlichen Ertrag auf Auffälligkeiten prüfen."},
    {"id": "pv_visual_roof", "name": "PV-Anlage Sichtprüfung", "category": "solar", "area_name": "Außenbereich", "icon": "mdi:solar-panel-large", "interval": 365, "interval_unit": "days", "priority": 3, "description": "Module auf offensichtliche Schäden oder Verschmutzung prüfen."},

    {"id": "robot_mower_blades", "name": "Rasenroboter Klingenwechsel", "category": "garden", "area_name": "Garten", "icon": "mdi:robot-mower-outline", "interval": 30, "interval_unit": "days", "priority": 3, "description": "Klingen prüfen oder tauschen."},
    {"id": "lawn_mower_service", "name": "Rasenmäher Wartung", "category": "garden", "area_name": "Garage", "icon": "mdi:grass", "interval": 365, "interval_unit": "days", "priority": 3, "description": "Messer, Öl, Luftfilter und Zündkerze prüfen."},
    {"id": "irrigation_check", "name": "Bewässerung prüfen", "category": "garden", "area_name": "Garten", "icon": "mdi:sprinkler-variant", "interval": 90, "interval_unit": "days", "priority": 2, "description": "Düsen, Leckagen und Zeitpläne prüfen."},
    {"id": "garden_tools", "name": "Gartengeräte prüfen", "category": "garden", "area_name": "Garage", "icon": "mdi:shovel", "interval": 365, "interval_unit": "days", "priority": 2, "description": "Akkus, Klingen, Stiele und Sicherheit prüfen."},
    {"id": "hedge_trimmer", "name": "Heckenschere warten", "category": "garden", "area_name": "Garage", "icon": "mdi:content-cut", "interval": 365, "interval_unit": "days", "priority": 2, "description": "Messer reinigen, ölen und Akkus prüfen."},

    {"id": "rain_gutter", "name": "Dachrinne reinigen", "category": "building", "area_name": "Außenbereich", "icon": "mdi:home-roof", "interval": 180, "interval_unit": "days", "priority": 4, "description": "Dachrinne auf Laub und Verstopfungen prüfen."},
    {"id": "roof_inspection", "name": "Dach Sichtprüfung", "category": "building", "area_name": "Außenbereich", "icon": "mdi:home-roof", "interval": 365, "interval_unit": "days", "priority": 4, "description": "Dach, Anschlüsse und sichtbare Schäden prüfen."},
    {"id": "window_seals", "name": "Fensterdichtungen pflegen", "category": "building", "area_name": "Haus", "icon": "mdi:window-closed-variant", "interval": 365, "interval_unit": "days", "priority": 2, "description": "Dichtungen reinigen und pflegen."},
    {"id": "door_locks", "name": "Türschlösser schmieren", "category": "building", "area_name": "Haus", "icon": "mdi:door-closed-lock", "interval": 365, "interval_unit": "days", "priority": 2, "description": "Schlösser und Beschläge prüfen und pflegen."},
    {"id": "facade_check", "name": "Fassade Sichtprüfung", "category": "building", "area_name": "Außenbereich", "icon": "mdi:home-search-outline", "interval": 365, "interval_unit": "days", "priority": 3, "description": "Risse, Feuchtigkeit und Schäden prüfen."},
    {"id": "garage_door", "name": "Garagentor warten", "category": "garage", "area_name": "Garage", "icon": "mdi:garage", "interval": 180, "interval_unit": "days", "priority": 3, "description": "Laufschienen, Federn, Sensoren und Antrieb prüfen."},

    {"id": "network_rack_check", "name": "Netzwerkschrank Sichtprüfung", "category": "it_network", "area_name": "IT/Netzwerk", "icon": "mdi:server-network", "interval": 90, "interval_unit": "days", "priority": 3, "description": "Lüftung, Kabel, USV und Geräte prüfen."},
    {"id": "nas_backup_check", "name": "NAS Backup prüfen", "category": "it_network", "area_name": "IT/Netzwerk", "icon": "mdi:nas", "interval": 30, "interval_unit": "days", "priority": 5, "description": "Letzte Backups und Restore-Fähigkeit prüfen."},
    {"id": "router_update_check", "name": "Router Updates prüfen", "category": "it_network", "area_name": "IT/Netzwerk", "icon": "mdi:router-network", "interval": 90, "interval_unit": "days", "priority": 3, "description": "Firmware-Updates und Konfigurationsbackup prüfen."},
    {"id": "wifi_check", "name": "WLAN Abdeckung prüfen", "category": "it_network", "area_name": "Haus", "icon": "mdi:wifi-check", "interval": 180, "interval_unit": "days", "priority": 2, "description": "Signalqualität und Client-Probleme prüfen."},

    {"id": "dryer_filter", "name": "Trockner Filter reinigen", "category": "household", "area_name": "Hauswirtschaft", "icon": "mdi:tumble-dryer", "interval": 14, "interval_unit": "days", "priority": 2, "description": "Flusenfilter und Wärmetauscher reinigen."},
    {"id": "washing_machine_clean", "name": "Waschmaschine reinigen", "category": "household", "area_name": "Hauswirtschaft", "icon": "mdi:washing-machine", "interval": 90, "interval_unit": "days", "priority": 2, "description": "Trommelreinigung, Flusensieb und Dichtungen prüfen."},
    {"id": "dishwasher_clean", "name": "Spülmaschine reinigen", "category": "household", "area_name": "Küche", "icon": "mdi:dishwasher", "interval": 60, "interval_unit": "days", "priority": 2, "description": "Sieb, Sprüharme und Maschinenpflege durchführen."},
    {"id": "refrigerator_coils", "name": "Kühlschrank Rückseite reinigen", "category": "household", "area_name": "Küche", "icon": "mdi:fridge-outline", "interval": 365, "interval_unit": "days", "priority": 1, "description": "Staub an Rückseite/Kondensator entfernen."},
    {"id": "vacuum_robot", "name": "Saugroboter Wartung", "category": "household", "area_name": "Haus", "icon": "mdi:robot-vacuum", "interval": 30, "interval_unit": "days", "priority": 2, "description": "Bürsten, Filter, Sensoren und Räder reinigen."},
    {"id": "air_purifier_filter", "name": "Luftreiniger Filter", "category": "household", "area_name": "Haus", "icon": "mdi:air-purifier", "interval": 180, "interval_unit": "days", "priority": 2, "description": "Filterzustand prüfen oder Filter wechseln."},
]
